FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/bank-webhook ./apps/bank-webhook
COPY packages ./packages/


RUN npm install

RUN npm run db:generate
RUN npm run build --workspace=packages/db
RUN npm run build --filter=apps/bank-webhook

CMD ["npm","run","start","--workspace=apps/bank-webhook"]