FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/bank-webhook ./apps/bank-webhook
COPY packages ./packages/

# Install dependencies
RUN npm install
# Can you add a script to the global package.json that does this?
RUN npm run db:generate
# 🧪 STEP 1: Generate Swagger JSON before build
WORKDIR /usr/src/apps/bank-webhook
RUN npm install --save-dev ts-node typescript
RUN npm run swagger:build

RUN npm run build --filter=apps/bank-webhook

CMD ["npm", "run", "start"]