FROM node:20.12.0-alpine3.19

WORKDIR /usr/src

COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/bank-server ./apps/bank-server

RUN npm install

RUN npm run db:generate
RUN npm run build --workspace=packages/db
RUN npm run build --filter=apps/bank-server

CMD [ "npm","run","start","--workspace=apps/bank-server" ]
EXPOSE 3004