FROM node:20.12.0-alpine3.19

WORKDIR /usr/src/app

# Build-time args (ADD THIS)
ARG NEXT_PUBLIC_WEBHOOK_URL

# Make them available during build
ENV NEXT_PUBLIC_WEBHOOK_URL=$NEXT_PUBLIC_WEBHOOK_URL

#for faster layer caching
COPY package.json package-lock.json turbo.json tsconfig.json ./

COPY apps/user-app ./apps/user-app
COPY packages ./packages


RUN npm install

RUN npm run db:generate

RUN npm run build --filter=apps/user-app

CMD ["npm", "run", "start-user-app"]